[theme]
# Configuración de colores
backgroundColor = "#1c1c1c"
secondaryBackgroundColor = "#2c2c2c"
textColor = "#ffffff"

# Configuración de fuentes
font = "Arial"
codeFont = "monospace"

# Configuración de la barra lateral
sidebarBackgroundColor = "#111111"
sidebarTextColor = "#ffffff"
sidebarBorderColor = "#333333"

# Configuración de la barra de título
headerBackgroundColor = "#111111"
headerTextColor = "#ffffff"
